### ISSUE TITLE
Kafka ingestion

### ISSUE THREAD

**Issue by lvh** [RackSec/desdemona#1]
Desdemona should be able to ingest Onyx segments through Kafka. This gives us better a better separation of concerns for deliverability of e.g. syslog messages: syslog talks to Kafka ([syslog-ng supports that][syslog-ng-kafka]), Kafka talks to Onyx which is also [already supported][onyx-kafka]. 

Kafka should probably piggyback on the Zookeeper cluster which Onyx is already running for us.

[syslog-ng-kafka]: https://github.com/balabit/syslog-ng-incubator/tree/master/modules/kafka/
[onyx-kafka]: https://github.com/onyx-platform/onyx-kafka

**Comment by sirsean** [comment]
This was resolved here: https://github.com/RackSec/desdemona/pull/21
