### ISSUE TITLE
Backport unified config.edn from onyx-template

### ISSUE THREAD

**Issue by lvh** [RackSec/desdemona#10]
See https://github.com/onyx-platform/onyx-template/blob/master/src/leiningen/new/onyx_app/resources/config.edn

This has the advantage of having a single `config.edn`, more reliant on environment variables, rather than a number of different ones for different environments.

**Comment by lvh** [comment]
This also grabs the onyx-id, meaning that onyx-id should no longer be an argument to `main`:

https://github.com/onyx-platform/onyx-template/commit/dc75d5b2aaafbb27790f958140ba989694fc3b29

**Comment by sirsean** [comment]
This is addressed here: https://github.com/RackSec/desdemona/pull/39
