### ISSUE TITLE
Enforce whitespace as part of CI

### ISSUE THREAD

**Issue by lvh** [RackSec/desdemona#19]
Right now, some files (e.g. `utils.clj`) had lines ending in whitespace. This was not caught by CI (kbiit and eastwood rely on post-reader data structures, so they wouldn't notice; neither did cljfmt). I noticed this while trying to get the codebase in a state that kibit would pass.

**Comment by reaperhulk** [comment]
Does it make sense to use something like `lein bikeshed` for this? It does trailing whitespace, trailing blank line, and line length checks. I'm unsure if we want to go down the PEP8 line length route, so maybe we turn that off?

**Comment by lvh** [comment]
Oh, right, lein bikeshed. Doesn't look super maintained, but I guess it doesn't really need to. I'm super surprised that in between cljfmt and bikeshed nothing complains about tabs.

**Comment by lvh** [comment]
I think the EditorConfig changes introduced by #23, #25 cover everything in this ticket.

**Comment by lvh** [comment]
re: bikeshed vs editorconfig; eclint handles tabs instead of spaces, and I don't think lein bikeshed does.

**Comment by ehashman** [comment]
Looks to have been closed by #26.
