### ISSUE TITLE
Add figwheel

### ISSUE THREAD

**Issue by smogg** [RackSec/desdemona#64]
We need live style injection and some css preprocessor (preferably SASS) compilation for easier front-end development. 
Sass compilation should be easy to implement:
https://github.com/bhauman/lein-figwheel/wiki/SASS-watcher

- [x] Figwheel
- [ ] CSS Preprocessing

**Comment by lvh** [comment]
Alas, this isn't really closed because @smogg thinks that I should set up SASS compilation + reloading for him as well ;)

**Comment by smogg** [comment]
Yeah, still can't make style-injection work. 
But it's not top-priority, I can deal without it for now
