### ISSUE TITLE
Use docker-compose

### ISSUE THREAD

**Issue by lvh** [RackSec/desdemona#7]
While desdemona is backed by Onyx, it necessarily has other requirements, including e.g. Kafka for ingestion. This is unlikely to be the last requirement. Once #2 is resolved, it would also be great to have e.g. a [mimic][mimic] running mimicking Rackspace Cloud Files. Finally, with [Carina][carina], it would be great if we can set up realistic demo/CI environments on some pretty big iron.

docker-compose gives us docker-quality repeatable environments that are easy to set up, and hopefully still enables production-grade setups.

As a side-effect of resolving this, we should consider having exactly 1 way to run things in development, mimicking the [new features in `onyx-template`][onyx-template] where possible. This means that `docker-compose up` should be the way you set up a development cluster, and setting up a production cluster should look as similar to that as possible.

[carina]: https://getcarina.com/
[onyx-template]: https://github.com/onyx-platform/onyx-template/blob/0.8.x/src/leiningen/new/onyx_app/docker-compose.yml

**Comment by lvh** [comment]
This is being done by @sirsean's work in #21.

**Comment by sirsean** [comment]
This is done in: https://github.com/RackSec/desdemona/pull/21
